"""removed superflous fk constraint on task table

Revision ID: 6af457c38537
Revises: dce8a38bbaf6
Create Date: 2025-05-12 23:42:37.169059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af457c38537'
down_revision = 'dce8a38bbaf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('task_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_foreign_key('task_ibfk_2', 'user', ['sent_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
