"""added column 'added_by' to task table for sending tasks to other users

Revision ID: d1f3db03c2ef
Revises: 
Create Date: 2025-05-12 23:28:31.764465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f3db03c2ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['sent_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sent_by')

    # ### end Alembic commands ###
