"""changed column name 'created_by' to 'owner' for clarity when sending tasks

Revision ID: dce8a38bbaf6
Revises: d1f3db03c2ef
Create Date: 2025-05-12 23:38:22.948497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dce8a38bbaf6'
down_revision = 'd1f3db03c2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.Integer(), nullable=True))
        batch_op.drop_constraint('task_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['owner'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('task_ibfk_1', 'user', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
